#!/bin/sh
#
## bootstrap

set -e

echo "Setting up your environment..."

#
# Check for Bundler
#
if test ! $(which bundle)
then
    echo "  x You need to install Bundler:"
    echo "    gem install bundler"
    exit
fi

#
# Install gems
#
bundle install --binstubs --path vendor/gems --without production

echo "Done!"
